---
# Launch instances, runs some tasks
# and then terminate them

- hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - aws-database-delete
    - aws-cluser-delete
    - aws-security-delete
    - aws-network-delete
  vars:
    - region: us-west-2
