---
# Launch instances, runs some tasks
# and then terminate them

- hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - aws-network-create
    - aws-security-create
    - aws-cluster-create
    - aws-database-create
  vars:
    - region: us-west-2
